#ifndef COMMUNICATOR_CONFIG_H
#define COMMUNICATOR_CONFIG_H

#define NUM_COMM_PORTS		1

#define COMM_PORTA			Serial
#define COMM_PORTA_BAUD		115200

#define TRANS_WAKEUP		3000
#define RECV_WAKEUP			5000
#define HEARTBEAT_WAKEUP	1000000
#define LOG_WAKEUP			5000
#define NUM_UPDATE_MESSAGES 3

#define NUM_MOTORS_SEND		4

#endif //COMMUNICATOR_CONFIG_H
